# Generated by Django 5.0.6 on 2024-07-07 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_com_app', '0006_alter_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
