# Generated by Django 5.0.6 on 2024-07-08 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_com_app', '0008_remove_order_customer_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
